// <auto-generated />
using MvvmCross.Platforms.Wpf.Views;

namespace MediaPlayer.WPF.Views
{
    /// <summary>
    /// Interaction logic for MediaPlayerView.xaml
    /// </summary>
    public partial class MediaLibraryView : MvxWpfView
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MediaLibraryView"/> class.
        /// </summary>
        public MediaLibraryView()
        {
            InitializeComponent();
        }
    }
}
