// <auto-generated />
using MediaPlayer.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MediaPlayer.Core.Migrations
{
    [DbContext(typeof(MediaDBContext))]
    [Migration("20230805165803_AddedMultiDiscCheck")]
    partial class AddedMultiDiscCheck
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("MediaPlayer.Models.Album", b =>
                {
                    b.Property<int>("AlbumID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlbumName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ArtistID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMultiDisc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.HasKey("AlbumID");

                    b.HasIndex("ArtistID");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("MediaPlayer.Models.Artist", b =>
                {
                    b.Property<int>("ArtistID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArtistName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Biography")
                        .HasColumnType("TEXT");

                    b.HasKey("ArtistID");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("MediaPlayer.Models.Contribution", b =>
                {
                    b.Property<int>("ContributionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtistID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrackID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ContributionID");

                    b.HasIndex("ArtistID");

                    b.HasIndex("TrackID");

                    b.ToTable("Contributions");
                });

            modelBuilder.Entity("MediaPlayer.Models.Disc", b =>
                {
                    b.Property<int>("DiscID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlbumID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiscName")
                        .HasColumnType("TEXT");

                    b.Property<int>("DiscNum")
                        .HasColumnType("INTEGER");

                    b.HasKey("DiscID");

                    b.HasIndex("AlbumID");

                    b.ToTable("Discs");
                });

            modelBuilder.Entity("MediaPlayer.Models.Genre", b =>
                {
                    b.Property<int>("GenreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GenreID");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("MediaPlayer.Models.Listing", b =>
                {
                    b.Property<int>("ListingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlaylistID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrackID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrackPos")
                        .HasColumnType("INTEGER");

                    b.HasKey("ListingID");

                    b.HasIndex("PlaylistID");

                    b.HasIndex("TrackID");

                    b.ToTable("Listings");
                });

            modelBuilder.Entity("MediaPlayer.Models.Playlist", b =>
                {
                    b.Property<int>("PlaylistID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaylistName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PlaylistID");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("MediaPlayer.Models.Track", b =>
                {
                    b.Property<int>("TrackID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("DiscID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lyrics")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("TrackLength")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TrackNum")
                        .HasColumnType("INTEGER");

                    b.HasKey("TrackID");

                    b.HasIndex("DiscID");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("MediaPlayer.Models.TrackGenre", b =>
                {
                    b.Property<int>("TrackGenreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenreID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrackID")
                        .HasColumnType("INTEGER");

                    b.HasKey("TrackGenreID");

                    b.HasIndex("GenreID");

                    b.HasIndex("TrackID");

                    b.ToTable("TrackGenres");
                });

            modelBuilder.Entity("MediaPlayer.Models.Album", b =>
                {
                    b.HasOne("MediaPlayer.Models.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("MediaPlayer.Models.Contribution", b =>
                {
                    b.HasOne("MediaPlayer.Models.Artist", "Artist")
                        .WithMany("Contributions")
                        .HasForeignKey("ArtistID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediaPlayer.Models.Track", "Track")
                        .WithMany("Contributions")
                        .HasForeignKey("TrackID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("MediaPlayer.Models.Disc", b =>
                {
                    b.HasOne("MediaPlayer.Models.Album", "Album")
                        .WithMany("Discs")
                        .HasForeignKey("AlbumID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("MediaPlayer.Models.Listing", b =>
                {
                    b.HasOne("MediaPlayer.Models.Playlist", "Playlist")
                        .WithMany("Listings")
                        .HasForeignKey("PlaylistID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediaPlayer.Models.Track", "Track")
                        .WithMany("Listings")
                        .HasForeignKey("TrackID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("MediaPlayer.Models.Track", b =>
                {
                    b.HasOne("MediaPlayer.Models.Disc", "Disc")
                        .WithMany("Tracks")
                        .HasForeignKey("DiscID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disc");
                });

            modelBuilder.Entity("MediaPlayer.Models.TrackGenre", b =>
                {
                    b.HasOne("MediaPlayer.Models.Genre", "Genre")
                        .WithMany("TrackGenres")
                        .HasForeignKey("GenreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediaPlayer.Models.Track", "Track")
                        .WithMany("TrackGenres")
                        .HasForeignKey("TrackID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("MediaPlayer.Models.Album", b =>
                {
                    b.Navigation("Discs");
                });

            modelBuilder.Entity("MediaPlayer.Models.Artist", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("Contributions");
                });

            modelBuilder.Entity("MediaPlayer.Models.Disc", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("MediaPlayer.Models.Genre", b =>
                {
                    b.Navigation("TrackGenres");
                });

            modelBuilder.Entity("MediaPlayer.Models.Playlist", b =>
                {
                    b.Navigation("Listings");
                });

            modelBuilder.Entity("MediaPlayer.Models.Track", b =>
                {
                    b.Navigation("Contributions");

                    b.Navigation("Listings");

                    b.Navigation("TrackGenres");
                });
#pragma warning restore 612, 618
        }
    }
}
