// <auto-generated />
using System.Windows.Controls;

namespace MediaPlayer.Pages
{
    /// <summary>
    /// Interaction logic for AlbumsPage.xaml
    /// </summary>
    public partial class AlbumsPage : Page
    {
        public AlbumsPage() => InitializeComponent();
    }
}
