// <auto-generated />
using System.Windows.Controls;

namespace MediaPlayer.Pages
{
    /// <summary>
    /// Interaction logic for AlbumsPage.xaml
    /// </summary>
    public partial class AlbumsPage : Page
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AlbumsPage"/> class.
        /// </summary>
        public AlbumsPage() => InitializeComponent();
    }
}
