// <auto-generated />
using System.Windows.Controls;

namespace MediaPlayer.Pages
{
    /// <summary>
    /// Interaction logic for ArtistsPage.xaml
    /// </summary>
    public partial class ArtistsPage : Page
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ArtistsPage"/> class.
        /// </summary>
        public ArtistsPage()
        {
            InitializeComponent();
        }
    }
}
