// <auto-generated />
using System.Windows.Controls;

namespace MediaPlayer.Pages
{
    /// <summary>
    /// Interaction logic for GenresPage.xaml
    /// </summary>
    public partial class GenresPage : Page
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GenresPage"/> class.
        /// </summary>
        public GenresPage()
        {
            InitializeComponent();
        }
    }
}
