// <auto-generated />
using System.Windows.Controls;

namespace MediaPlayer.Pages
{
    /// <summary>
    /// Interaction logic for PlaylistsPage.xaml
    /// </summary>
    public partial class PlaylistsPage : Page
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PlaylistsPage"/> class.
        /// </summary>
        public PlaylistsPage()
        {
            InitializeComponent();
        }
    }
}
