// <auto-generated />
using System.Windows.Controls;

namespace MediaPlayer.Pages
{
    /// <summary>
    /// Interaction logic for SinglePlaylistPage.xaml
    /// </summary>
    public partial class SinglePlaylistPage : Page
    {
        public SinglePlaylistPage()
        {
            InitializeComponent();
        }
    }
}
