// <auto-generated />
using System.Windows.Controls;

namespace MediaPlayer.Pages
{
    /// <summary>
    /// Interaction logic for SinglePlaylistPage.xaml
    /// </summary>
    public partial class SinglePlaylistPage : Page
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SinglePlaylistPage"/> class.
        /// </summary>
        public SinglePlaylistPage()
        {
            InitializeComponent();
        }
    }
}
