// <auto-generated />
using System.Windows.Controls;

namespace MediaPlayer.Pages
{
    /// <summary>
    /// Interaction logic for pgTracks.xaml
    /// </summary>
    public partial class TracksPage : Page
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TracksPage"/> class.
        /// </summary>
        public TracksPage()
        {
            InitializeComponent();
        }
    }
}
