// <auto-generated />
using System.Windows.Controls;

namespace MediaPlayer.Pages
{
    /// <summary>
    /// Interaction logic for pgTracks.xaml
    /// </summary>
    public partial class TracksPage : Page
    {
        public TracksPage()
        {
            InitializeComponent();
        }
    }
}
