// <auto-generated />
using System.Windows.Controls;

namespace MediaPlayer.Pages
{
    /// <summary>
    /// Interaction logic for YearsPage.xaml
    /// </summary>
    public partial class YearsPage : Page
    {
        public YearsPage()
        {
            InitializeComponent();
        }
    }
}
