// <auto-generated />
using System.Windows.Controls;

namespace MediaPlayer.Pages
{
    /// <summary>
    /// Interaction logic for YearsPage.xaml
    /// </summary>
    public partial class YearsPage : Page
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="YearsPage"/> class.
        /// </summary>
        public YearsPage()
        {
            InitializeComponent();
        }
    }
}
